package de.rub.RKE.keminterfaces;

//Interface for the public-private Key pair, which is used and generated by the KEM
public interface KemKeyPair {

	public KemPublicKey getPublicKey();
	
	public KemPrivateKey getPrivateKey();
}
