package de.rub.RKE.keminterfaces;


//Interface for the symmetric key, which is generated by the KEM
public interface KemOutputKey {

	//TODO:Discuss if we can require that classes work on bytes[]. Might change to abstract class otherwise.
	public byte[] getKeyBytes();
}
