package de.rub.RKE.ecieskem;

import org.bouncycastle.crypto.params.KeyParameter;

import de.rub.RKE.keminterfaces.KemOutputKey;

//Datatype/Class for the symmetric Key which is generated by the ECIES KEM
public class EciesOutputKey extends KeyParameter implements KemOutputKey{

	public EciesOutputKey(byte[] key) {
		super(key);
	}
	
	public EciesOutputKey(KeyParameter key) {
		super(key.getKey());
	}
	
	public byte[] getKeyBytes() {
		return super.getKey();
	}
	
}
